theme = "after-dark"
base_url = "/"
compile_sass = false

taxonomies = [
    # You can enable/disable RSS
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]
[markdown]
highlight_code = true

[extra]
author = "PoPi"
after_dark_menu = [
    { name = "Home", url = "/", weight = 0 },
    { name = "Blog", url = "/blog", weight = 1 },
]
socials = [ ]
paginate_by = 15
