theme = "after-dark"
base_url = "https://www.popi.tech/blog"
compile_sass = true

taxonomies = [
    # You can enable/disable RSS
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]
[markdown]
highlight_code = true

[extra]
author = "PoPi"
after_dark_menu = [
    { name = "Home", url = "$BASE_URL", weight = 0 },
    { name = "Blog", url = "$BASE_URL/blog", weight = 1 },
]
socials = [ ]
paginate_by = 15
